############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2

[[main]]
name = "Catagories"
url = "/categories"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 4

[[main]]
weight = 5
name = "Pages"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"

# footer menu
[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 1
