############# English navigation ##############

# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "博客"
url = "/blog"
weight = 2

[[main]]
name = "归档"
url = "/categories"
weight = 3

[[main]]
name = "关于"
url = "/about"
weight = 4

# footer menu
[[footer]]
name = "隐私政策"
url = "/privacy-policy"
weight = 1
